### ISSUE TITLE
Behavior of Meta namespace and OnSettingsSave

### ISSUE THREAD

**Issue by chipsTM** [openplanet-nl/openplanet-issues#365] opened 2023-09-13 03:27 UTC
Here's a basic example of what I was describing the other day. 
It doesn't flush the file to disk with the correct value until the second save. (despite the `curSettings` containing the updated value)

```
auto plugin = Meta::ExecutingPlugin();
void OnSettingsSave(Settings::Section& section) {
    auto curSettings = plugin.GetSetting("data");
    curSettings.WriteString("saved?");
}

[Setting hidden]
string data;

void Main() {
    while(true){
        yield();
        auto curSettings = plugin.GetSetting("data");
        if (curSettings is null) continue;
        print(curSettings.ReadString()); // this will show updated, but not in Settings.ini file (until you save again a second time)
        sleep(10000);
    }
}
```

**Comment by codecat** [comment] 2023-09-15 10:39
I can't reproduce this. Using the following test plugin, the data is saved correctly as expected.
```asc
void OnSettingsSave(Settings::Section& section) {
	section.SetString("data", "hello world");
}
```

**Comment by codecat** [comment] 2023-09-15 10:41
Sidenote - your code doesn't really make sense to me: why are you getting the setting like that? Why can't you just do `data = "saved?";`?

**Comment by codecat** [comment] 2024-02-27 12:00
Closing because I still can't reproduce this.

**Closed as not planned by codecat** 2024-02-27 12:00 UTC
Labels: bug, api, can't reproduce
