### ISSUE TITLE
Plugin manager crashing when trying to sort plugins.

### ISSUE THREAD

**Issue by MazerMP** [openplanet-nl/openplanet-issues#149] opened 2022-07-03 12:51 UTC
Trying to sort the plugin manager by last updated or newest causes it to crash in TM²
![image](https://user-images.githubusercontent.com/12106036/177040296-2c222408-1857-4513-83d0-47a544325218.png)
![image](https://user-images.githubusercontent.com/12106036/177040324-fcb7970f-6195-4608-a2e1-7eaf27b33d9a.png)
![image](https://user-images.githubusercontent.com/12106036/177040483-ea8f270e-8006-4f17-9400-63e3aae723f6.png)

**Comment by codecat** [comment] 2022-07-03 19:26
Duplicate of #142

**Closed as completed by codecat** 2022-07-03 19:26 UTC
