### ISSUE TITLE
`no state` on calling `req.Finished()` for an in-prog request (this happens when the request resolves)

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#316] opened 2023-05-08 07:19 UTC
Code:

```
        @step3Req = Net::HttpPost("http://74.234.75.72:80/itemrefresh/create_map", Json::Write(items));
        // sleep(5000); // uncomment this to fix
        while (!step3Req.Finished()) {
            yield();
        }
        if (step3Req.ResponseCode() != 200) {
            return;
        }
```

This is the same pattern I've used before I'm pretty sure, and I've never run into this problem. logs just show `Script exception: no state` with a reference to the line calling .Finished().

I know the request works fine, b/c if I just sleep for 5s instead then I can access stuff.

I have no idea what's going on, but AFAIK my code should work fine.

**Comment by XertroV** [comment] 2023-05-09 09:14
Additionally, if .Finished is called and `no state` is thrown, then it will *always* be thrown. so this can't be `try {} catch {}`ed

**Comment by codecat** [comment] 2023-05-11 13:41
I am unable to reproduce this 🤔

**Comment by XertroV** [comment] 2023-05-11 13:49
Neither can I now. :/
(I made a version of e++ that *should* have the bug, but can't replicate)

**Comment by codecat** [comment] 2023-05-11 14:01
So there are a couple of reasons why this "no state" exception could be happening:

1. You are calling `Finished` before calling `Start` (`HttpPost`/`HttpGet`/etc will call this implicitly)
2. You are calling `Finished` after calling `String`/`Buffer`/`SaveToFile`/etc

In your code you don't show that happening, but perhaps you still had like this in your code somewhere?

Judging by your naming conventions, maybe you accidentally checked `step2Req.Finished()` instead of `step3Req.Finished()` 🤔

**Comment by XertroV** [comment] 2023-05-11 14:03
> 1. You are calling Finished before calling Start (HttpPost/HttpGet/etc will call this implicitly)

I was using HttpPost to begin with, and have always called .Start in the other code I used. 

> 2. You are calling Finished after calling String/Buffer/SaveToFile/etc

Pretty sure this isn't it, all that code is after a tight loop of `while (!req.Finished()) yield():`

> Judging by your naming conventions, maybe you accidentally checked step2Req.Finished() instead of step3Req.Finished()

`step3Req` is the only http request.

**Comment by XertroV** [comment] 2023-05-11 14:05
This is the code in question. it's on a branch called `repro-error` (even tho it doesn't)
https://github.com/XertroV/tm-editor-plus-plus/blob/cd1b741b5505a80bb0cca4d79eefb820933922cc/src/Components/Inventory/EmbedItems.as#L257-L279

**Comment by codecat** [comment] 2023-05-11 14:05
I can't think of any other case where this might happen. I'll leave this on the backburner for now. If you have a reproduction case, I can look into this again.

**Comment by codecat** [comment] 2024-02-27 12:27
Closing for now.

**Closed as not planned by codecat** 2024-02-27 12:27 UTC
Labels: bug, api, support, can't reproduce
