### ISSUE TITLE
Missing `UI::EndCombo()` can crash the game

### ISSUE THREAD

**Issue by XertroV** [openplanet-nl/openplanet-issues#289] opened 2023-04-09 07:45 UTC
this was within a table. UI stack was like:

```
- settings
  - table
    - row
      - column
        - combo without ::EndCombo
```

Can put together a reproduction if you want

**Comment by codecat** [comment] 2023-04-09 17:12
I can't reproduce this:
```asc
[SettingsTab name="Asdf"]
void Asdf() {
	UI::BeginCombo("Foo", "Bar");
}
```
Can you give me a minimal reproduction case?

**Comment by codecat** [comment] 2023-04-22 11:59
I can't reproduce this with the following code either:
```asc
[SettingsTab name="Asdf"]
void Asdf()
{
	if (UI::BeginTable("Test", 2)) {
		UI::TableSetupColumn("First", UI::TableColumnFlags::WidthStretch, 0.5f);
		UI::TableSetupColumn("Second", UI::TableColumnFlags::WidthStretch, 0.5f);
		UI::TableHeadersRow();

		UI::TableNextColumn();
		UI::BeginCombo("Foo", "Bar");

		UI::TableNextColumn();
		UI::Text("Foobar");

		UI::EndTable();
	}
}
```

**Comment by codecat** [comment] 2023-05-02 12:14
Have you been able to reproduce this?

**Comment by codecat** [comment] 2024-02-27 12:20
Closing for now.

**Closed as not planned by codecat** 2024-02-27 12:20 UTC
Labels: bug, api, crash, can't reproduce
