### ISSUE TITLE
Website not updating cotd wins since 9months

### ISSUE THREAD

**Issue by Nikls1** [openplanet-nl/openplanet-issues#435] opened 2024-03-05 19:21 UTC
![Screenshot (13)](https://github.com/openplanet-nl/issues/assets/162367918/3f6aba37-9d78-49ee-8178-10d389a049d3)
![Screenshot (8)](https://github.com/openplanet-nl/issues/assets/162367918/3362d38a-f0ce-49d4-8365-976928a09126)
![Screenshot (7)](https://github.com/openplanet-nl/issues/assets/162367918/c7dd423e-effa-4be2-9888-767aebeea4a2)
could you update your website.

**Comment by davidbmaier** [comment] 2024-03-05 19:22
You'll have to be more specific about what's wrong.
The website is getting updates fairly frequently - if you think something's broken or incorrect you'll need to let us know to give us a chance to fix it.

**Comment by codecat** [comment] 2024-03-05 20:17
Your last 2 screenshot is 12 days old - [your profile](https://trackmania.io/#/player/2c1a1411-4af7-44f8-9b03-4dc997cecdac/cotd) seems to be updating just fine.

Have you checked if you see the correct stats if you select "include reruns"? It looks like that puts your win count at 5 as opposed to 4.

**Comment by codecat** [comment] 2024-03-10 16:13
Not entirely sure what the issue is, so I'll close this for now.

**Closed as not planned by codecat** 2024-03-10 16:13 UTC
