### ISSUE TITLE
add way to check number of elements in `enum`

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/openplanet-issues#509] opened 2024-07-01 18:41 UTC
Not sure if it's possible but it would be nice to know how many elements have been defined in an enum so I can loop through them more easily. Also, if possible, add a way to get an array of defined values.

```Angelscript
enum MyEnum {
    value1 = -1,
    value2 = 0,
    value3 = 5
}

uint valueCount = Enum::Count(MyEnum);  // returns 3
int[] values = Enum::Values(MyEnum);  // returns { -1, 0, 5 }
```

**Comment by codecat** [comment] 2024-07-01 19:07
Duplicate of #48

**Closed as not planned by codecat** 2024-07-01 19:07 UTC
